tinyMCE.addI18n('tr.fullpage_dlg',{
title:"Belge özellikleri",
meta_tab:"Genel",
appearance_tab:"Görünüm",
advanced_tab:"Gelişmiş",
meta_props:"Meta Bilgisi",
langprops:"Dil ve Kodlama",
meta_title:"Başlık",
meta_keywords:"Anahtar Kelimeler",
meta_description:"Açıklama",
meta_robots:"Robot",
doctypes:"Döküman Tipi",
langcode:"Dil Kodu",
langdir:"Dil Yönü",
ltr:"Soldan sağa",
rtl:"Sağdan sola",
xml_pi:"XML larasyon",
encoding:"Karakter kodlaması",
appearance_bgprops:"Arkaplan ayarları",
appearance_marginprops:"Gövde hizalama",
appearance_linkprops:"Bağlantı renkleri",
appearance_textprops:"Yazı seçenekleri",
bgcolor:"Arkaplan rengi",
bgimage:"Arkaplan resmi",
left_margin:"Soldan uzaklık",
right_margin:"Sağdab uzaklık",
top_margin:"Üstten uzaklık",
bottom_margin:"Alttan uzaklık",
text_color:"Yazı rengi",
font_size:"Yazı boyu",
font_face:"Yazı stili",
link_color:"Bağlantı rengi",
hover_color:"Üzerine gelindiğinde",
visited_color:"Ziyaret edildiğinde",
active_color:"Aktiv olduğunda",
textcolor:"Renk",
fontsize:"Yazı boyutu",
fontface:"Yazı Tipi",
meta_index_follow:"Index and follow the links",
meta_index_nofollow:"Index and don't follow the links",
meta_noindex_follow:"Do not index but follow the links",
meta_noindex_nofollow:"Do not index and don\'t follow the links",
appearance_style:"Stil dosyası ve stil ayarları",
stylesheet:"Stil dosyası",
style:"Stil",
author:"Yazar",
copyright:"Telif Hakkı",
add:"Yeni element ekle",
remove:"Seçili elementi sil",
moveup:"Seçili elementi yukarı taşı",
movedown:"Seçili elementi aşağı taşı",
head_elements:"Baş elementler",
info:"Bilgi",
add_title:"Başlık ekle",
add_meta:"Meta ekle",
add_script:"Script ekle",
add_style:"Stil ekle",
add_link:"Bağlantı ekle",
add_base:"Base ekle",
add_comment:"Yorum ekle",
title_element:"Başlık",
script_element:"Script",
style_element:"Stil",
base_element:"Base",
link_element:"Bağlantı",
meta_element:"Meta",
comment_element:"Yorum",
src:"Src",
language:"Dil",
href:"Href",
target:"Target",
type:"Type",
charset:"Charset",
defer:"Defer",
media:"Media",
properties:"Properties",
name:"Name",
value:"Value",
content:"Content",
rel:"Rel",
rev:"Rev",
hreflang:"Href lang",
general_props:"Genel",
advanced_props:"Gelişmiş"
});