tinyMCE.addI18n('tr.xhtmlxtras_dlg',{
attribute_label_title:"Başlık",
attribute_label_id:"ID",
attribute_label_class:"Class",
attribute_label_style:"Stil",
attribute_label_cite:"Aktarma",
attribute_label_datetime:"Tarih/Zaman",
attribute_label_langdir:"Metin Yönü",
attribute_option_ltr:"Soldan sağa",
attribute_option_rtl:"Sağdan sola",
attribute_label_langcode:"Dil",
attribute_label_tabindex:"Sekme indeksi",
attribute_label_accesskey:"Erişim anahtarı",
attribute_events_tab:"Olaylar",
attribute_attrib_tab:"Öznitelikleri",
general_tab:"General",
attrib_tab:"Öznitelikleri",
events_tab:"Olaylar",
fieldset_general_tab:"Genel ayarlar",
fieldset_attrib_tab:"Element Öznitelikleri",
fieldset_events_tab:"Element Olayları",
title_ins_element:"Element ekle",
title_del_element:"Element sil",
title_acronym_element:"Element kısalt",
title_abbr_element:"Element kısalt",
title_cite_element:"Element alıntı",
remove:"Kaldır",
insert_date:"Şuanki Tarih/Zaman Ekle",
option_ltr:"Soldan sağa",
option_rtl:"Sağdan sola",
attribs_title:"Öznitelikleri Ekle/Düzenle"
});