tinyMCE.addI18n('tr.advanced',{
style_select:"Sitller",
font_size:"Yazı boyutu",
fontdefault:"Yazı tipi",
block:"Tür",
paragraph:"Paragraf",
div:"Div",
address:"Adres",
pre:"Preformatted",
h1:"Başlık 1",
h2:"Başlık 2",
h3:"Başlık 3",
h4:"Başlık 4",
h5:"Başlık 5",
h6:"Başlık 6",
blockquote:"Blockquote",
code:"Kod",
samp:"Kod örneği",
dt:"Definition term ",
dd:"Definition description",
bold_desc:"Kalın (Ctrl+B)",
italic_desc:"Italik (Ctrl+I)",
underline_desc:"Altı Çizili (Ctrl+U)",
striketrough_desc:"Strikethrough",
justifyleft_desc:"Sola hizalı",
justifycenter_desc:"Ortaya hizalı",
justifyright_desc:"Sağa hizalı",
justifyfull_desc:"Tam hizalı",
bullist_desc:"Sıralanmamış liste",
numlist_desc:"Sıralanmış liste",
outdent_desc:"Outdent",
indent_desc:"Indent",
undo_desc:"Geri Al (Ctrl+Z)",
redo_desc:"İler Al (Ctrl+Y)",
link_desc:"Bağlantı Ekle/Düzenle",
unlink_desc:"Bağlantıyı kaldır",
image_desc:"Resim Ekle/Düzenle",
cleanup_desc:"Cleanup messy code",
code_desc:"HTML Kaynağını düzenle",
sub_desc:"Subscript",
sup_desc:"Superscript",
hr_desc:"Yatay cetvel ekle",
removeformat_desc:"Remove formatting",
custom1_desc:"Özel açıklamanız buraya",
forecolor_desc:"Yazı sitilini seç",
backcolor_desc:"Arkaplan rengini seç",
charmap_desc:"Özel karakter ekle",
visualaid_desc:"Toggle guidelines/invisible elements",
anchor_desc:"Insert/edit anchor",
cut_desc:"Kes",
copy_desc:"Kopyala",
paste_desc:"Yapıştır",
image_props_desc:"Resim özellikleri",
newdocument_desc:"Yeni döküman",
help_desc:"Yardım",
blockquote_desc:"Blockquote",
clipboard_msg:"Kopyala/Kes/Yapıştır fonksiyonlarını Mozilla ve Firefox programlarında kullanamazsınız.\nBu konuyla ilgili daha fazla bilgi edinmek istiyormusunuz?",
path:"Yol",
newdocument:"Tüm elementleri temizlemek istediğinizden eminmisiniz?",
toolbar_focus:"Araç çubuğuna geçmek için - Alt+Q, Editör modunda geçmek için - Alt-Z, Element moduna geçmek için - Alt-X",
more_colors:"Daha fazla renk"
});