tinyMCE.addI18n('tr.advanced_dlg',{
about_title:"TinyMCE Hakkında",
about_general:"Hakkında",
about_help:"Yardım",
about_license:"Lisans",
about_plugins:"Ek Paketler",
about_plugin:"Ek Paker",
about_author:"Yazar",
about_version:"Versiyon",
about_loaded:"Yüklenen Ek Paketler",
anchor_title:"Insert/edit anchor",
anchor_name:"Anchor name",
code_title:"HTML Kaynak Kod Editörü",
code_wordwrap:"Word wrap",
colorpicker_title:"Renk seçin",
colorpicker_picker_tab:"Seçici",
colorpicker_picker_title:"Renk seçici",
colorpicker_palette_tab:"Palet",
colorpicker_palette_title:"Palet renkleri",
colorpicker_named_tab:"Adlandırıldı",
colorpicker_named_title:"Adlandırılmış renkler",
colorpicker_color:"Renk:",
colorpicker_name:"Adı:",
charmap_title:"Özel karakter seç",
image_title:"Resim Ekle/Düzenle",
image_src:"Resim bağlantısı",
image_alt:"Resim açıklaması",
image_list:"Resim listesi",
image_border:"Kenarlık",
image_dimensions:"Boyutlar",
image_vspace:"Dikey boşluk",
image_hspace:"Yatay boşluk",
image_align:"Hizalama",
image_align_baseline:"Baseline",
image_align_top:"Üst",
image_align_middle:"Orta",
image_align_bottom:"Alt",
image_align_texttop:"Yazı üstte",
image_align_textbottom:"Yazı altta",
image_align_left:"Sol",
image_align_right:"Sağ",
link_title:"Bağlantı Ekle/Düzenle",
link_url:"Bağlantı adresi",
link_target:"Hedef",
link_target_same:"Bağlantıyı aynı pencerede aç",
link_target_blank:"Bağlantıyı yeni pencerede aç",
link_titlefield:"Başlık",
link_is_email:"Girmiş olduğunuz bağlantı adresi e-posta adresine benziyor, gerekli olan mailto: ön ekini girmek istiyormusunuz?",
link_is_external:"Giirmiş olduğunuz bağlantı bir dış bağlantıya benziyor, gerekli olan http:// ön ekini girmek istiyormusunuz?",
link_list:"Bağlantı listesi"
});