tinyMCE.addI18n('tr.advlink_dlg',{
title:"Bağlantı Ekle/Düzenle",
url:"Bağlantı Adresi",
target:"Hedef",
titlefield:"Başlık",
is_email:"Girmiş olduğunuz bağlantı adresi bir e-posta adresine benziyor, zorunlu olan mailto: önekini eklemek istiyormusunuz?",
is_external:"Girmiş olduğunuz bağlantı adresi bir dış bağlantıya benziyor, zorunlu olan http:// önekini eklemek istiyormusunuz?",
list:"Bağlantı Listesi",
general_tab:"Genel",
popup_tab:"Açılır Pencere",
events_tab:"Etkinlikler",
advanced_tab:"Advanced",
general_props:"Genel Ayarlar",
popup_props:"Açılık Pencere Ayarları",
event_props:"Etkinlikler",
advanced_props:"Gelişmiş Ayarlar",
popup_opts:"Ayarlar",
anchor_names:"Sunucu",
target_same:"Aynı pencerede aç",
target_parent:"Yan pencerede aç",
target_top:"Üst çerçevede aç (Tüm çerçeveleri değiştirir)",
target_blank:"Yeni pencerede aç",
popup:"Javascript Açılır pencere",
popup_url:"Açılır pencere bağlantısı",
popup_name:"Pencere adı",
popup_return:"Insert 'return false'",
popup_scrollbars:"Kaydırgaçları göster",
popup_statusbar:"Durum çubuğunu göster",
popup_toolbar:"Araç çubuğunu göster",
popup_menubar:"Menü çubuğunu göster",
popup_location:"Adres çubuğunu göster",
popup_resizable:"Pencereyi boyutlandırılabilir yap",
popup_dependent:"Bağlı (sadece Mozilla/Firefox)",
popup_size:"Boy",
popup_position:"Pozisyon (X/Y)",
id:"Id",
style:"Sitil",
classes:"Sınıf",
target_name:"Hedef adı",
langdir:"Dil yönü",
target_langcode:"Hedef dili",
langcode:"Dil kodu",
encoding:"Hedef karakter kodlaması",
mime:"Hedef MIME tipi",
rel:"Sayfayı hedefe ilişkilendir",
rev:"Hedefi sayfaya ilişkilendir",
tabindex:"Sekme indexi",
accesskey:"Giriş Anahtarı",
ltr:"Soldan sağa",
rtl:"Sağdan sola",
link_list:"Bağlantı listesi"
});