tinyMCE.addI18n('tr.advimage_dlg',{
tab_general:"Genel",
tab_appearance:"Görünüm",
tab_advanced:"Gelişmiş",
general:"Genel",
title:"Başlık",
preview:"Önizleme",
constrain_proportions:"Ölçüleri koru",
langdir:"Dil yönü",
langcode:"Dil kodu",
long_desc:"Uzun bağlantı açıklaması",
style:"Sitil",
classes:"Sınıf",
ltr:"Soldan sağa",
rtl:"Sağdan sola",
id:"Id",
map:"Resim haritası",
swap_image:"Resmi değiştir",
alt_image:"Alternatif resim",
mouseover:"fare üzerine geldiğinde",
mouseout:"fare üzerinden gittiğinde",
misc:"Çeşitli",
example_img:"Görünüm önizleme",
missing_alt:"Resim açıklaması eklemeden devam etmek istediğinizden emin misiniz? Resim açıklaması olmadan bazı kullanıcıların engellemelerinden dolayı : yazı tarayıcısı kullanıyor olabilir, yada internet tarayıcısından resimler kapalı bir şekilde bakıyor olabilir .",
dialog_title:"Resim Ekle/Düzenle",
src:"Resim bağlantısı",
alt:"Resim açıklaması",
list:"Resim listesi",
border:"Kenarlık",
dimensions:"Boyutlar",
vspace:"Dikey boşluk",
hspace:"Yatay boşluk",
align:"Hizalama",
align_baseline:"Bulunduğu Yerde",
align_top:"Üst",
align_middle:"Orta",
align_bottom:"Alt",
align_texttop:"Yazı üstte",
align_textbottom:"Yazı altta",
align_left:"Sol",
align_right:"Sağ",
image_list:"Resim listesi"
});