tinyMCE.addI18n('tr.media_dlg',{
title:"Medya Ekle/Düzenle",
general:"Genel",
advanced:"Gelişmiş",
file:"Dosya/ADRES",
list:"Liste",
size:"Boyutlar",
preview:"Önizleme",
constrain_proportions:"Oranları Koru",
type:"Tip",
id:"Id",
name:"Ad",
class_name:"Class",
vspace:"D-Boşluk",
hspace:"Y-Boşluk",
play:"Otomatik oynat",
loop:"Döngü",
menu:"Menüyü göster",
quality:"Kalite",
scale:"Ölçek",
align:"Hizalama",
salign:"SHizamala",
wmode:"WModu",
bgcolor:"Arkaplan",
base:"Base",
flashvars:"Flashvars",
liveconnect:"SWLiveConnect",
autohref:"AutoHREF",
cache:"Bellek",
hidden:"Gizli",
controller:"Kontroller",
kioskmode:"Kiosk modu",
playeveryframe:"Her kareyi oynat",
targetcache:"Hedef önbelleği",
correction:"Düzeltme yok",
enablejavascript:"JavaScript Aktiv et",
starttime:"Başlangıç zamanı",
endtime:"Bitiş zamanı",
href:"Href",
qtsrcchokespeed:"Kısma hızı",
target:"Hedef",
volume:"Ses",
autostart:"Otomatik başlat",
enabled:"Aktive edildi",
fullscreen:"Tam ekran",
invokeurls:"Adresleri Çağır",
mute:"Sessiz",
stretchtofit:"Streç uygun",
windowlessvideo:"Penceresiz Video",
balance:"Denge",
baseurl:"Base URL",
captioningid:"Altyazı id",
currentmarker:"Şuanki işaretleyici",
currentposition:"Şuanki pozisyon",
defaultframe:"Varsayılan kare",
playcount:"Sayımı oynat",
rate:"Oran",
uimode:"UI Modu",
flash_options:"Flash ayarları",
qt_options:"Quicktime ayarları",
wmp_options:"Windows media player ayarları",
rmp_options:"Real media player ayarları",
shockwave_options:"Shockwave ayarları",
autogotourl:"Otomatik URL'ye git",
center:"Orta",
imagestatus:"Resim durumu",
maintainaspect:"Boyutları koru",
nojava:"Java Yok",
prefetch:"Önceden Al",
shuffle:"Karıştır",
console:"Konsol",
numloop:"Num loops",
controls:"Kontroller",
scriptcallbacks:"Script callbacks",
swstretchstyle:"Stretch style",
swstretchhalign:"Stretch H-Align",
swstretchvalign:"Stretch V-Align",
sound:"Sound",
progress:"Progress",
qtsrc:"QT Src",
qt_stream_warn:"Streamed rtsp resources should be added to the QT Src field under the advanced tab.\nYou should also add a non streamed version to the Src field..",
align_top:"Üst",
align_right:"Sağ",
align_bottom:"Alt",
align_left:"Sol",
align_center:"Orta",
align_top_left:"Sol üst",
align_top_right:"Sağ üst",
align_bottom_left:"Alt sol",
align_bottom_right:"Alt sağ",
flv_options:"Flash video ayarları",
flv_scalemode:"Scale mode",
flv_buffer:"Bellek",
flv_startimage:"Başlangıç resmi",
flv_starttime:"Başlangıç zamanı",
flv_defaultvolume:"Varsayılan Ses",
flv_hiddengui:"Gizli GUI",
flv_autostart:"Otomatik Başlat",
flv_loop:"Loop",
flv_showscalemodes:"Show scale modes",
flv_smoothvideo:"Smooth video",
flv_jscallback:"JS Callback"
});