tinyMCE.addI18n('en.style_dlg',{
title:"CSS Stilini Düzenle",
apply:"Uygula",
text_tab:"İçerik",
background_tab:"Arkaplan",
block_tab:"Blok",
box_tab:"Kutu",
border_tab:"Kenarlık",
list_tab:"Liste",
positioning_tab:"Pozisyon",
text_props:"İçerik",
text_font:"Yazı Tipi",
text_size:"Boyut",
text_weight:"Genişlik",
text_style:"Stil",
text_variant:"Varyant",
text_lineheight:"Satır yüksekliği",
text_case:"Durum",
text_color:"Renk",
text_decoration:"Dekorasyon",
text_overline:"Hat üzerinde",
text_underline:"Altı çizili",
text_striketrough:"Üstü çizili",
text_blink:"blink",
text_none:"none",
background_color:"Arkaplan rengi",
background_image:"Arkaplan resmi",
background_repeat:"Tekrarla",
background_attachment:"Ek Dosya",
background_hpos:"Yatay pozisyon",
background_vpos:"Dikey pozisyon",
block_wordspacing:"Kelime aralığı",
block_letterspacing:"Harf aralığı",
block_vertical_alignment:"Dikey hizalama",
block_text_align:"Metin hizalama",
block_text_indent:"Metin girdisi",
block_whitespace:"Boşluk",
block_display:"Ekran",
box_width:"Genişlik",
box_height:"Yükseklik",
box_float:"Float",
box_clear:"Clear",
padding:"Padding",
same:"Same for all",
top:"Üst",
right:"Sağ",
bottom:"Alt",
left:"Sol",
margin:"Kenar",
style:"Style",
width:"Width",
height:"Height",
color:"Color",
list_type:"Type",
bullet_image:"Bullet image",
position:"Position",
positioning_type:"Type",
visibility:"Visibility",
zindex:"Z-index",
overflow:"Overflow",
placement:"Placement",
clip:"Clip"
});