tinyMCE.addI18n('tr.table_dlg',{
general_tab:"Genel",
advanced_tab:"Gelişmiş",
general_props:"Genel Seçenekler",
advanced_props:"Gelişmiş seçenekler",
rowtype:"Row in table part",
title:"Tablo Ekle/Düzenle",
width:"Genişlik",
height:"Yükseklik",
cols:"Kolon",
rows:"Satır",
cellspacing:"Hücre aralığı",
cellpadding:"Hücre dolgusu",
border:"Kenarlık",
align:"Hizalama",
align_default:"Varsayılan",
align_left:"Sol",
align_right:"Sağ",
align_middle:"Orta",
row_title:"Tablo satırı özellikleri",
cell_title:"Tablo hücresi özellikleri",
cell_type:"Hücre Tipi",
valign:"Dikey hizalama",
align_top:"Üst",
align_bottom:"Alt",
bordercolor:"Kenarlık rengi",
bgcolor:"Arkaplan rengi",
merge_cells_title:"Tablo hücrelerini birleştir",
id:"Id",
style:"Stil",
langdir:"Dil yönü",
langcode:"Dil kodu",
mime:"Hedef MIME tipi",
ltr:"Soldan sağa",
rtl:"Sağdan sola",
bgimage:"Arkaplan rengi",
summary:"Özet",
td:"Veri",
th:"Başlık",
cell_cell:"Mevcut hücreyi güncelle",
cell_row:"Satırdaki hücreleri güncelle",
cell_all:"Tablodaki tüm hücreleri güncelle",
row_row:"Bulunduğum satırı güncelle",
row_odd:"Tablodaki satırı düzenle",
row_even:"Tablodaki tüm satırları düzenle",
row_all:"Tablodaki tüm satırları düzenle",
thead:"Tablo başlığı",
tbody:"Tablo gövdesi",
tfoot:"Tablo altı",
scope:"Kapsam",
rowgroup:"Satır grubu",
colgroup:"Kolon grubu",
col_limit:"Maksimun sütun sayısını aşmışsınız {$cols}.",
row_limit:"Maksimun satır sayısını aşmışsınız {$rows}.",
cell_limit:"Maksimun hücre sayısını aşmışsınız {$cells}.",
missing_scope:"Eğer bu tablo başlık hücresi için bir kapsam belirlemeden devam etmek istediğinizden emin misiniz. O olmadan, bazı engelli kullanıcıların içerik veya tablonun görüntülenen verileri anlamaları zor olabilir.",
caption:"Tablo başlığı",
frame:"Çerçeve",
frame_none:"hiçbiri",
frame_groups:"gruplar",
frame_rows:"Satırlar",
frame_cols:"Hücreler",
frame_all:"Hepsi",
rules:"Kurallar",
rules_void:"geçersiz",
rules_above:"yukarıda",
rules_below:"aşağıda",
rules_hsides:"hsides",
rules_lhs:"lhs",
rules_rhs:"rhs",
rules_vsides:"vsides",
rules_box:"kutu",
rules_border:"kenarlık"
});